language: node_js
node_js:
 - 0.10.26
before_install:
 - git config user.email "ryan.p.durling@gmail.com"
 - git config user.name "RyanDur"
 - gem install compass
 - npm install -g grunt-cli
after_success:
 - cat $DEPLOY_KEY > .travis/deploy_key.pem
 - chmod 600 .travis/deploy_key.pem # this key should have push access
 - ssh-add .travis/deploy_key.pem
 - grunt gh-pages

