language: node_js
node_js:
- 0.10.26
before_install:
- git config --global user.email "ryan.p.durling@gmail.com"
- git config --global user.name "RyanDur"
- gem install compass
- npm install -g grunt-cli
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- grunt gh-pages
env:
  global:
    secure: EDs9tSSghFl6MM4/kSpuyjK8T+mjIAE8e/RNuwui1nh4p5wPe3pZusmJhu13n1fZsObyQvM9PCv4VawaM8bMkTDNazz+Or1TRaIxz0oTFaUB10ZEyLmcDT/KF8nnj8c/dJAWqxzQy6LrybZAcOdikLomjVODKeLcjX2io0kMWT8=
